books_data = {
    1: {"title": "1984", "author": "George Orwell"},
    2: {"title": "To Kill a Mockingbird", "author": "Harper Lee"},
    3: {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald"},
    4: {"title": "Moby Dick", "author": "Herman Melville"},
    5: {"title": "Pride and Prejudice", "author": "Jane Austen"},
    6: {"title": "War and Peace", "author": "Leo Tolstoy"},
    7: {"title": "The Hobbit", "author": "J.R.R. Tolkien"},
    8: {"title": "The Catcher in the Rye", "author": "J.D. Salinger"},
    9: {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky"},
    10: {"title": "The Alchemist", "author": "Paulo Coelho"},
    11: {"title": "Brave New World", "author": "Aldous Huxley"},
    12: {"title": "The Lord of the Rings", "author": "J.R.R. Tolkien"},
    13: {"title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling"},
    14: {"title": "The Kite Runner", "author": "Khaled Hosseini"},
    15: {"title": "The Book Thief", "author": "Markus Zusak"},
    16: {"title": "The Chronicles of Narnia", "author": "C.S. Lewis"},
    17: {"title": "Anna Karenina", "author": "Leo Tolstoy"},
    18: {"title": "Don Quixote", "author": "Miguel de Cervantes"},
    19: {"title": "The Hunger Games", "author": "Suzanne Collins"},
    20: {"title": "The Da Vinci Code", "author": "Dan Brown"},
}

users_data = {
    1: {"name": "Alice"},
    2: {"name": "Bob"},
    3: {"name": "Charlie"},
    4: {"name": "Diana"},
    5: {"name": "Ethan"},
    6: {"name": "Fiona"},
    7: {"name": "George"},
    8: {"name": "Hannah"},
    9: {"name": "Ivan"},
    10: {"name": "Julia"},
}